<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="jest tests" tests="6" failures="4" errors="0" time="8.438">
  <testsuite name="__tests__\second.test.js" errors="0" failures="1" skipped="1" timestamp="2023-02-11T10:43:51" time="2.03" tests="2">
    <testcase classname="" name="Timeout test" time="0.002">
      <failure>: Timeout - Async callback was not invoked within the 1 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 1 ms timeout specified by jest.setTimeout.Error: 
    at new Spec (D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\node_modules\jest-jasmine2\build\jasmine\Spec.js:116:22)
    at new Spec (D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\node_modules\jest-jasmine2\build\setup_jest_globals.js:78:9)
    at specFactory (D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\node_modules\jest-jasmine2\build\jasmine\Env.js:523:24)
    at Env.it (D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\node_modules\jest-jasmine2\build\jasmine\Env.js:592:24)
    at Env.it (D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:134:23)
    at it (D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\node_modules\jest-jasmine2\build\jasmine\jasmineLight.js:100:21)
    at Object.&lt;anonymous&gt; (D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\__tests__\second.test.js:1:34)
    at Runtime._execModule (D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\node_modules\jest-runtime\build\index.js:1245:24)
    at Runtime._loadModule (D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\node_modules\jest-runtime\build\index.js:844:12)
    at Runtime.requireModule (D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\node_modules\jest-runtime\build\index.js:694:10)
    at jasmine2 (D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\node_modules\jest-jasmine2\build\index.js:230:13)
    at runTestInternal (D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\node_modules\jest-runner\build\runTest.js:380:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runTest (D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\node_modules\jest-runner\build\runTest.js:472:34)
    at Object.worker (D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\node_modules\jest-runner\build\testWorker.js:133:12)</failure>
    </testcase>
    <testcase classname="" name="Skipped test" time="0">
      <skipped/>
    </testcase>
  </testsuite>
  <testsuite name="__tests__\main.test.js" errors="0" failures="3" skipped="0" timestamp="2023-02-11T10:43:51" time="2.039" tests="4">
    <testcase classname="Test 1" name="Passing test" time="0.001">
    </testcase>
    <testcase classname="Test 1 › Test 1.1" name="Failing test" time="0.002">
      <failure>Error: expect(received).toBeTruthy()

Received: false
    at Object.&lt;anonymous&gt; (D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\__tests__\main.test.js:10:21)
    at Object.asyncJestTest (D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:106:37)
    at D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\node_modules\jest-jasmine2\build\queueRunner.js:45:12
    at new Promise (&lt;anonymous&gt;)
    at mapper (D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\node_modules\jest-jasmine2\build\queueRunner.js:28:19)
    at D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\node_modules\jest-jasmine2\build\queueRunner.js:75:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)</failure>
    </testcase>
    <testcase classname="Test 1 › Test 1.1" name="Exception in target unit" time="0.001">
      <failure>Error: Some error
    at Object.throwError (D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\lib\main.js:2:9)
    at Object.&lt;anonymous&gt; (D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\__tests__\main.test.js:14:11)
    at Object.asyncJestTest (D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:106:37)
    at D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\node_modules\jest-jasmine2\build\queueRunner.js:45:12
    at new Promise (&lt;anonymous&gt;)
    at mapper (D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\node_modules\jest-jasmine2\build\queueRunner.js:28:19)
    at D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\node_modules\jest-jasmine2\build\queueRunner.js:75:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)</failure>
    </testcase>
    <testcase classname="Test 2" name="Exception in test" time="0">
      <failure>Error: Some error
    at Object.&lt;anonymous&gt; (D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\__tests__\main.test.js:21:11)
    at Object.asyncJestTest (D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:106:37)
    at D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\node_modules\jest-jasmine2\build\queueRunner.js:45:12
    at new Promise (&lt;anonymous&gt;)
    at mapper (D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\node_modules\jest-jasmine2\build\queueRunner.js:28:19)
    at D:\NarF\Documents\IdeaProjects\Dr-Horv\test-execution-report\reports\jest\node_modules\jest-jasmine2\build\queueRunner.js:75:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)</failure>
    </testcase>
  </testsuite>
</testsuites>